Metrics/LineLength:
  Max: 100
  Exclude:
    - 'self_data.gemspec'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AndOr:
  EnforcedStyle: conditionals
